### ISSUE TITLE
New translation

### ISSUE THREAD

**Issue by hartois** [h44z/kopano_webapp_contactimporter#3]
Please help me with adding new translation)
I'm do next:
- copy directory languages/en_US.UTF-8 to languages/ru_RU.UTF-8
- edit languages/ru_RU.UTF-8/LC_MESSAGES/plugin_calendarimporter.po
- build plugin, upload it

But in UI I see all messages of plugin in english.
I'm trying clear browser cache, re-login to webapp, restart php-fpm...
In JS console Translation obect does not have contactimporter plugin property:
![scr6565](https://user-images.githubusercontent.com/11641656/41408201-8f163514-6fda-11e8-94a7-e8a1bc6e651b.png)

What I'm doing wrong?

**Comment by h44z** [comment]
Can you share your .po file? I will try to reproduce the problem.

**Comment by hartois** [comment]
[plugin_calendarimporter.po.txt](https://github.com/h44z/kopano_webapp_contactimporter/files/2104943/plugin_calendarimporter.po.txt)

**Comment by h44z** [comment]
I found the issue :) The filenames of the translation are wrong (plugin_calendarimporter.po should be plugin_contactimporter.po).

I have commited the fix to my repo (including your russian translation). Hope it works now!

**Comment by hartois** [comment]
Thank you!
